version: '3'
services:
  # mirushot:
  #   build: ./prd
  #   volumes:
  #     - .mirusho:/src/.venv
  #     - ./prd:/src
  #   ports:
  #     - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する
  dev_mirusho:
    build: ./dev
    container_name: 'dev_mirusho'
    tty: true
    volumes:
      # - ./dev/.venv:/src/.venv
      - "./dev:/app"
    ports:
      - 8000:8000  # ホストマシンのポート8000を、docker内のポート8000に接続する